name: xcube-gedi
channels:
  - conda-forge
  - defaults
dependencies:
  # Required
  - python>=3.10
  - xarray
  - xcube >= 1.9.0
  - pip
  - pip:
      - gedidb
  # for testing
  - black
  - flake8
  - pytest