name: Unittest xcube-gedi

on:
  push:
  release:
    types: [ published ]

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout xcube-gedi
        uses: actions/checkout@v4

      - name: Set up MicroMamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml

      - name: Install and Test
        shell: bash -l {0}
        run:
          pytest test/ --cov=xcube_gedi --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}